[platformio]
src_dir = esp32_marauder
lib_dir = libraries
default_envs = cyd40

[env:cyd40]
platform = espressif32@6.10.0
board = lolin_d32
framework = arduino
lib_ldf_mode = deep+
lib_ignore =
    Arduino-Ra01S
    LittleFS_esp32

monitor_speed = 115200
upload_speed = 115200

board_build.f_flash = 80000000L
board_build.partitions = min_spiffs.csv
board_build.filesystem = spiffs

build_flags =
    -D CYD_40

; The E32R40T has the same ST7796/XPT2046 interface and pinout as this setup.
lib_deps =
    symlink://libraries/TFT_eSPI-CYD/3.5R/TFT_eSPI-master
